CREATE DATABASE IF NOT EXISTS dynamic_dual_grid
  CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;

USE dynamic_dual_grid;

CREATE TABLE IF NOT EXISTS users (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  name VARCHAR(128) NOT NULL,
  email VARCHAR(255) NULL,
  role VARCHAR(32) NOT NULL DEFAULT 'user',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  password_salt VARCHAR(64) NULL,
  password_hash VARCHAR(255) NULL,
  last_login_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  INDEX idx_users_role (role),
  INDEX idx_users_status (status)
);

CREATE TABLE IF NOT EXISTS exchange_accounts (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  exchange_name VARCHAR(64) NOT NULL,
  market_type VARCHAR(64) NOT NULL,
  account_label VARCHAR(128) NOT NULL,
  testnet BOOLEAN NOT NULL DEFAULT TRUE,
  dry_run BOOLEAN NOT NULL DEFAULT TRUE,
  api_key_ref TEXT NULL,
  api_key_fingerprint VARCHAR(64) NULL,
  secret_ref TEXT NULL,
  permissions_json JSON NULL,
  hedge_mode_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_exchange_accounts_user FOREIGN KEY (user_id) REFERENCES users(id),
  INDEX idx_exchange_accounts_user (user_id),
  INDEX idx_exchange_accounts_status (status)
);

CREATE TABLE IF NOT EXISTS strategy_instances (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(64) NOT NULL UNIQUE,
  user_id BIGINT NOT NULL,
  exchange_account_id BIGINT NOT NULL,
  strategy_name VARCHAR(128) NOT NULL,
  strategy_version VARCHAR(64) NOT NULL,
  mode VARCHAR(32) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'created',
  config_version VARCHAR(64) NOT NULL DEFAULT 'v1',
  config_json JSON NOT NULL,
  live_confirm VARCHAR(128) NULL,
  started_at TIMESTAMP(6) NULL,
  stopped_at TIMESTAMP(6) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_strategy_instances_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_strategy_instances_account FOREIGN KEY (exchange_account_id) REFERENCES exchange_accounts(id),
  INDEX idx_strategy_instances_user (user_id),
  INDEX idx_strategy_instances_account (exchange_account_id),
  INDEX idx_strategy_instances_status (status)
);

CREATE TABLE IF NOT EXISTS account_run_configs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(96) NOT NULL UNIQUE,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  enabled BOOLEAN NOT NULL DEFAULT TRUE,
  mode VARCHAR(32) NOT NULL DEFAULT 'plan_only',
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  symbols_json JSON NOT NULL,
  symbol_budget_json JSON NOT NULL,
  base_position_usdt DECIMAL(28, 8) NOT NULL DEFAULT 0,
  max_single_order_usdt DECIMAL(28, 8) NOT NULL DEFAULT 0,
  allow_reduce_only BOOLEAN NOT NULL DEFAULT TRUE,
  allow_add_position BOOLEAN NOT NULL DEFAULT FALSE,
  allow_market_orders BOOLEAN NOT NULL DEFAULT FALSE,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_account_run_configs_account FOREIGN KEY (exchange_account_id) REFERENCES exchange_accounts(id),
  CONSTRAINT fk_account_run_configs_strategy FOREIGN KEY (strategy_instance_id) REFERENCES strategy_instances(id),
  UNIQUE KEY uk_account_run_configs_account_strategy (exchange_account_id, strategy_instance_id),
  INDEX idx_account_run_configs_status (status)
);

CREATE TABLE IF NOT EXISTS execution_plans (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  external_id VARCHAR(96) NOT NULL UNIQUE,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  direction VARCHAR(16) NULL,
  mode VARCHAR(32) NOT NULL DEFAULT 'plan_only',
  status VARCHAR(32) NOT NULL DEFAULT 'planned',
  reason VARCHAR(255) NOT NULL,
  trigger_json JSON NULL,
  action_plan_json JSON NOT NULL,
  risk_checks_json JSON NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_execution_plans_account FOREIGN KEY (exchange_account_id) REFERENCES exchange_accounts(id),
  CONSTRAINT fk_execution_plans_strategy FOREIGN KEY (strategy_instance_id) REFERENCES strategy_instances(id),
  INDEX idx_execution_plans_account_time (exchange_account_id, created_at),
  INDEX idx_execution_plans_status (status),
  INDEX idx_execution_plans_event_type (event_type)
);

CREATE TABLE IF NOT EXISTS symbol_allocations (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  budget_usdt DECIMAL(28, 8) NOT NULL,
  base_position_usdt DECIMAL(28, 8) NOT NULL,
  max_symbol_drawdown_pct DECIMAL(18, 10) NOT NULL,
  max_gross_exposure_ratio DECIMAL(18, 10) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'active',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_symbol_allocations_strategy FOREIGN KEY (strategy_instance_id) REFERENCES strategy_instances(id),
  UNIQUE KEY uk_symbol_allocations_strategy_symbol (strategy_instance_id, symbol),
  INDEX idx_symbol_allocations_status (status)
);

CREATE TABLE IF NOT EXISTS symbol_states (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  strategy_instance_id BIGINT NOT NULL,
  exchange_account_ref VARCHAR(64) NOT NULL DEFAULT '',
  symbol VARCHAR(32) NOT NULL,
  state VARCHAR(64) NOT NULL,
  base_price DECIMAL(28, 12) NOT NULL,
  base_qty DECIMAL(28, 12) NOT NULL DEFAULT 0,
  high_since_base DECIMAL(28, 12) NULL,
  low_since_base DECIMAL(28, 12) NULL,
  trend_extreme_price DECIMAL(28, 12) NULL,
  last_price DECIMAL(28, 12) NULL,
  long_qty DECIMAL(28, 12) NOT NULL DEFAULT 0,
  short_qty DECIMAL(28, 12) NOT NULL DEFAULT 0,
  long_entry_price DECIMAL(28, 12) NULL,
  short_entry_price DECIMAL(28, 12) NULL,
  realized_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  long_unrealized_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  short_unrealized_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  fee_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  slippage_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  funding_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  profit_transfer_count_in_trend INT NOT NULL DEFAULT 0,
  loss_side_reduce_count_in_trend INT NOT NULL DEFAULT 0,
  recovery_count_in_trend INT NOT NULL DEFAULT 0,
  trend_exit_candidate_count INT NOT NULL DEFAULT 0,
  last_transfer_tick INT NOT NULL DEFAULT -999999,
  last_loss_reduce_tick INT NOT NULL DEFAULT -999999,
  last_transfer_price DECIMAL(28, 12) NULL,
  last_loss_reduce_price DECIMAL(28, 12) NULL,
  tick_count INT NOT NULL DEFAULT 0,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_symbol_states_strategy FOREIGN KEY (strategy_instance_id) REFERENCES strategy_instances(id),
  UNIQUE KEY uk_symbol_states_strategy_account_symbol (strategy_instance_id, exchange_account_ref, symbol)
);

CREATE TABLE IF NOT EXISTS market_snapshots (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  timestamp TIMESTAMP(6) NOT NULL,
  user_id BIGINT NOT NULL,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  price DECIMAL(28, 12) NOT NULL,
  mark_price DECIMAL(28, 12) NULL,
  state VARCHAR(64) NOT NULL,
  long_qty DECIMAL(28, 12) NOT NULL,
  short_qty DECIMAL(28, 12) NOT NULL,
  long_unrealized_pnl DECIMAL(28, 8) NOT NULL,
  short_unrealized_pnl DECIMAL(28, 8) NOT NULL,
  realized_pnl DECIMAL(28, 8) NOT NULL,
  net_exposure DECIMAL(28, 8) NOT NULL,
  gross_exposure DECIMAL(28, 8) NOT NULL,
  equity DECIMAL(28, 8) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX idx_market_snapshots_strategy_symbol_time (strategy_instance_id, symbol, timestamp)
);

CREATE TABLE IF NOT EXISTS strategy_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  event_uid VARCHAR(64) NOT NULL UNIQUE,
  parent_event_id BIGINT NULL,
  timestamp TIMESTAMP(6) NOT NULL,
  user_id BIGINT NOT NULL,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  direction VARCHAR(16) NULL,
  state_before VARCHAR(64) NOT NULL,
  state_after VARCHAR(64) NULL,
  trigger_json JSON NULL,
  sizing_json JSON NULL,
  action_plan_json JSON NULL,
  realized_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  fee_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  slippage_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'planned',
  error_message TEXT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX idx_strategy_events_strategy_symbol_time (strategy_instance_id, symbol, timestamp),
  INDEX idx_strategy_events_type (event_type)
);

CREATE TABLE IF NOT EXISTS trade_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  trade_uid VARCHAR(64) NOT NULL UNIQUE,
  strategy_event_id BIGINT NULL,
  timestamp TIMESTAMP(6) NOT NULL,
  user_id BIGINT NOT NULL,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NOT NULL,
  event_type VARCHAR(64) NOT NULL,
  side VARCHAR(16) NOT NULL,
  position_side VARCHAR(16) NOT NULL,
  action VARCHAR(32) NOT NULL,
  price DECIMAL(28, 12) NOT NULL,
  fill_price DECIMAL(28, 12) NOT NULL,
  qty DECIMAL(28, 12) NOT NULL,
  notional DECIMAL(28, 8) NOT NULL,
  fee DECIMAL(28, 8) NOT NULL DEFAULT 0,
  slippage_cost DECIMAL(28, 8) NOT NULL DEFAULT 0,
  funding_fee DECIMAL(28, 8) NOT NULL DEFAULT 0,
  realized_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  reason VARCHAR(255) NOT NULL,
  status VARCHAR(32) NOT NULL DEFAULT 'filled',
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_trade_events_strategy_event FOREIGN KEY (strategy_event_id) REFERENCES strategy_events(id),
  INDEX idx_trade_events_strategy_symbol_time (strategy_instance_id, symbol, timestamp)
);

CREATE TABLE IF NOT EXISTS risk_events (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  timestamp TIMESTAMP(6) NOT NULL,
  user_id BIGINT NULL,
  exchange_account_id BIGINT NULL,
  strategy_instance_id BIGINT NULL,
  symbol VARCHAR(32) NULL,
  risk_level VARCHAR(32) NOT NULL,
  risk_type VARCHAR(64) NOT NULL,
  action_taken VARCHAR(64) NOT NULL,
  message TEXT NOT NULL,
  context_json JSON NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  INDEX idx_risk_events_time (timestamp),
  INDEX idx_risk_events_strategy_symbol (strategy_instance_id, symbol)
);

CREATE TABLE IF NOT EXISTS daily_reports (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  report_date DATE NOT NULL,
  user_id BIGINT NOT NULL,
  exchange_account_id BIGINT NOT NULL,
  strategy_instance_id BIGINT NOT NULL,
  symbol VARCHAR(32) NULL,
  start_equity DECIMAL(28, 8) NULL,
  end_equity DECIMAL(28, 8) NULL,
  daily_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  daily_pnl_pct DECIMAL(18, 10) NOT NULL DEFAULT 0,
  gross_profit DECIMAL(28, 8) NOT NULL DEFAULT 0,
  gross_loss DECIMAL(28, 8) NOT NULL DEFAULT 0,
  fee_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  slippage_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  funding_total DECIMAL(28, 8) NOT NULL DEFAULT 0,
  net_pnl DECIMAL(28, 8) NOT NULL DEFAULT 0,
  max_drawdown DECIMAL(28, 8) NOT NULL DEFAULT 0,
  long_max_qty DECIMAL(28, 12) NOT NULL DEFAULT 0,
  short_max_qty DECIMAL(28, 12) NOT NULL DEFAULT 0,
  max_net_exposure DECIMAL(28, 8) NOT NULL DEFAULT 0,
  max_gross_exposure DECIMAL(28, 8) NOT NULL DEFAULT 0,
  profit_transfer_count INT NOT NULL DEFAULT 0,
  loss_side_reduce_count INT NOT NULL DEFAULT 0,
  position_recovery_count INT NOT NULL DEFAULT 0,
  rebalance_count INT NOT NULL DEFAULT 0,
  trade_count INT NOT NULL DEFAULT 0,
  markdown_path VARCHAR(512) NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  UNIQUE KEY uk_daily_reports_scope (report_date, strategy_instance_id, symbol),
  INDEX idx_daily_reports_user_date (user_id, report_date),
  CONSTRAINT fk_daily_reports_user FOREIGN KEY (user_id) REFERENCES users(id),
  CONSTRAINT fk_daily_reports_account FOREIGN KEY (exchange_account_id) REFERENCES exchange_accounts(id),
  CONSTRAINT fk_daily_reports_strategy FOREIGN KEY (strategy_instance_id) REFERENCES strategy_instances(id)
);

CREATE TABLE IF NOT EXISTS admin_audit_logs (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  audit_uid VARCHAR(64) NOT NULL UNIQUE,
  admin_user_id BIGINT NOT NULL,
  action_type VARCHAR(64) NOT NULL,
  target_user_id BIGINT NULL,
  target_account_id BIGINT NULL,
  target_strategy_id BIGINT NULL,
  target_symbol VARCHAR(32) NULL,
  before_value_json JSON NULL,
  after_value_json JSON NULL,
  reason VARCHAR(255) NOT NULL,
  created_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  CONSTRAINT fk_admin_audit_logs_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
  INDEX idx_admin_audit_logs_admin_time (admin_user_id, created_at)
);

CREATE TABLE IF NOT EXISTS app_runtime_state (
  state_key VARCHAR(64) PRIMARY KEY,
  payload_json JSON NOT NULL,
  updated_at TIMESTAMP(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)
);
