<template>
  <StrategyCenterPage v-if="store.activeRoute !== 'strategy'" />
  <section v-else class="page active strategy-hub-page">
    <article class="panel data-overview-card strategy-overview-card">
      <div class="data-overview-head"><div><h2>策略中心</h2><p class="muted">先看每套规则在找什么、现在是否工作，再进入详情检查规则。</p></div><button class="button ghost small" :disabled="busy" @click="refresh">{{ busy ? "刷新中…" : "刷新策略" }}</button></div>
      <div class="data-overview-metrics strategy-overview-metrics"><div><span>全部策略</span><strong>{{ cards.length }}</strong><small>套已配置规则</small></div><div><span>自动执行</span><strong>1</strong><small>机器负责调仓</small></div><div><span>推给你决定</span><strong>3</strong><small>你决定是否交易</small></div><div><span>今日信号</span><strong>{{ signals.length }}</strong><small>个已记录机会</small></div></div>
    </article>
    <div v-if="store.strategyCatalogError || store.signalDeskError" class="service-alert">{{ store.strategyCatalogError || store.signalDeskError }} <button class="button ghost small" @click="refresh">重试</button></div>
    <section v-for="group in groups" :key="group.title" class="panel strategy-group">
      <div class="strategy-group-head"><div><h3>{{ group.title }}</h3><p>{{ group.description }}</p></div><span>{{ group.items.length }} 套</span></div>
      <div class="strategy-row-columns" aria-hidden="true"><span>策略与用途</span><span>最近形态</span><span>当前动态</span><span>状态</span></div>
      <div class="strategy-row-list">
        <article v-for="item in group.items" :key="item.slug" class="strategy-directory-row">
          <div class="strategy-row-name"><span class="eyebrow">{{ item.kind }}</span><h3>{{ item.name }}</h3><p>{{ item.summary }}</p></div>
          <StrategyThumbnail :points="item.points" :signal="item.signal" :empty-text="item.emptyText" />
          <div class="strategy-row-dynamics"><span v-for="metric in item.metrics" :key="metric.label"><small>{{ metric.label }}</small><b>{{ metric.value }}</b></span></div>
          <div class="strategy-row-state"><StatusBadge :text="item.status" :color="item.color" /><small>{{ item.reason }}</small><button class="button ghost small" @click="setActivePage(`strategy/${item.slug}`)">查看详情</button></div>
        </article>
      </div>
    </section>
  </section>
</template>
<script setup>
import{computed,onMounted,watch}from"vue";import StatusBadge from"../components/StatusBadge.vue";import StrategyThumbnail from"../components/StrategyThumbnail.vue";import StrategyCenterPage from"./StrategyCenterPage.vue";import{isAuthenticated,loadSignalDesk,loadStrategyCatalog,setActivePage,store}from"../stores/appStore.js";
const signals=computed(()=>store.signalDesk?.signals||[]);const busy=computed(()=>store.strategyCatalogBusy||store.signalDeskBusy);const weights=computed(()=>store.state?.trend_forward?.runner?.weights||{});const holdingCount=computed(()=>Object.values(weights.value).filter(v=>Math.abs(Number(v))>1e-9).length);const universeSize=computed(()=>store.selectedStrategy?.spec?.symbols?.length||0);const serviceEnabled=computed(()=>Boolean(store.signalDesk?.operations?.service?.enabled));const equityPoints=computed(()=>(store.state?.live_reconciliation?.equity?.points||[]).map(r=>Number(r.paper_normalized)).filter(Number.isFinite));
const familyEntries=computed(()=>Object.entries(store.signalDesk?.recent_samples_by_family||{}));const count=p=>signals.value.filter(r=>p.test(String(r.family_id||r.family||r.type||""))).length;const rollingCount=p=>Object.entries(store.signalDesk?.rolling_30d_by_family||{}).reduce((sum,[family,value])=>sum+(p.test(family)?Number(value):0),0);const dailyAverage=id=>Number(store.signalDesk?.rolling_30d_daily_average_by_family?.[id]||0);const sample=p=>signals.value.find(r=>p.test(String(r.family_id||r.family||r.type||"")))||familyEntries.value.find(([family])=>p.test(family))?.[1]?.[0]||null;const prices=s=>[...(s?.chart_before||[]),...(s?.chart_after||[]),...(s?.simulation?.chart_after||[])].map(r=>Number(r.close)).filter(Number.isFinite);const familyControl=id=>store.signalDesk?.operations?.family_controls?.[id]||{};
const cards=computed(()=>{const forward=store.state?.trend_forward;const trendStarted=Boolean(forward?.status&&forward.status!=="NOT_STARTED");const trendFresh=trendStarted&&forward?.data_fresh!==false;const make=(slug,familyId,name,summary,pattern,empty)=>{const s=sample(pattern);const control=familyControl(familyId);const service=store.signalDesk?.operations?.service;let status="未部署 / 状态未知",color="orange",reason="暂时没有读到扫描服务状态";if(service){if(!service.enabled||control.enabled===false){status="已停用";reason=control.disabled_reason||"提醒服务已关闭"}else if(service.running&&service.market_data_fresh){status="扫描正常运行";color="green";reason="最近一轮扫描已成功"}else{status="已启用但扫描超时";color="red";reason="超过 30 分钟没有成功扫描"}}return{slug,name,kind:"推给你决定",summary,signal:s,points:prices(s),emptyText:empty,status,color,reason,metrics:[{label:"今日推送",value:`${count(pattern)} 个`},{label:"近 30 天",value:`${rollingCount(pattern)} 个`},{label:"实际日均",value:`${dailyAverage(familyId).toFixed(2)} 个`}]}};return[{slug:"trend",name:store.selectedStrategy?.name||"多周期趋势",kind:"自动执行",summary:store.selectedStrategy?.summary||"策略定义暂时不可用。",points:equityPoints.value,emptyText:"等待净值记录",status:!forward?"状态未知":!trendStarted?"尚未启动":trendFresh?"运行中":"数据超时",color:trendFresh?"green":"orange",reason:trendFresh?"按冻结目标自动调仓":"检查前向数据和运行状态",metrics:[{label:"当前持仓",value:`${holdingCount.value} / ${universeSize.value||'—'}`},{label:"前向进度",value:forward?.elapsed_days==null?"—":`${forward.elapsed_days} 天`}]},make("breakout","BREAKOUT_MOMENTUM","放量突破","价格冲破近期高点、成交明显放大时提醒你。",/break|突破/i,"尚无突破样本"),make("oversold","OVERSOLD_REBOUND","高位回调","上涨途中一次急跌后出现企稳迹象时提醒你。",/oversold|超跌/i,"尚无回调样本"),make("strength","SUSTAINED_STRENGTH","持续强势","价格连续走强、成交持续活跃时提醒你。",/strong|强势/i,"尚无强势样本")]});
const groups=computed(()=>[{title:"自动执行",description:"机器按规则决策，你只需查看结果和风险。",items:cards.value.filter(i=>i.kind==="自动执行")},{title:"推给你决定",description:"系统筛选机会，是否交易由你判断。",items:cards.value.filter(i=>i.kind==="推给你决定")}]);function refresh(){loadStrategyCatalog();loadSignalDesk()}onMounted(()=>{if(isAuthenticated.value)refresh()});watch(isAuthenticated,v=>{if(v)refresh()});
</script>
